CREATE TABLE OT.TBL_DATAACCESS (
  ID            VARCHAR2(50 BYTE) DEFAULT SYS_GUID(),
  EMPLOYEE_ID   NUMBER,
  FIRST_NAME    VARCHAR2(50 BYTE),
  LAST_NAME     VARCHAR2(50 BYTE),
  EMAIL_ADDRESS VARCHAR2(50 BYTE),
  CONSTRAINT PK_TBL_DATAACCESS_ID PRIMARY KEY (ID) USING INDEX TABLESPACE SYSTEM STORAGE (INITIAL 64 K
                                                                                          MAXEXTENTS UNLIMITED)
)
TABLESPACE SYSTEM
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;